### PR TITLE
Allow use of relative app path

### PR DESCRIPTION
**Pull request by ivoronin**
`__dirname` points to directory of the current module

### CODE REVIEW

**Comment by sindresorhus** [comment]
Is using a relative path actually not working for you?

**Comment by ivoronin** [comment]
Yes, its not working, `__dirname` points to script's directory:
```js
// test.js
var process = require('process');

console.log("__dirname", __dirname)
console.log("cwd", process.cwd())
```
```
$ pwd
/Users/ivoronin
$ node /var/tmp/test.js 
__dirname /private/var/tmp
cwd /Users/ivoronin
```

**Comment by sindresorhus** [comment]
The use of `__dirname` was intentional. I could also have made the `appBath` an absolute path, but this works too.

**Comment by sindresorhus** [comment]
Thanks :)

**Pull request merged**
